In [41]:
import pandas as pd
import glob

In [42]:
jsonfiles = [f for f in glob.glob("..\json_files_3\*.json")]

In [43]:
temp = pd.DataFrame()
df1 =  pd.DataFrame()

In [44]:
for f in jsonfiles:
    temp = pd.read_json(path_or_buf=f, orient = 'values')
    df1 = pd.concat([df1, temp], ignore_index=True)

In [45]:
#df1.to_csv("abstracts.csv")

In [46]:
df1.head()

,abstract_full,application_date,application_number,application_type,assignees,citations,claims_full,classifications,country,ipc_classes,...,ipc_subgroups,priority_date,provisional_date,provisional_number,publication_date,publication_number,related_document_numbers,tags,tags_text,title
0,Techniques for constructing an enhanced model ...,2010-04-28,13002249,utility,[EMPIRE TECHNOLOGY DEVELOPMENT LLC],[],1. A method for constructing a model of a surf...,"{'cpc_classifications': None, 'ipc_classificat...",US,[G06F],...,[G06F 17/50],2010-04-28,NaN,NaN,2012-11-29,US20120303332,[],"[, determining_pressure, _6, 13, generate, _16...",determining_pressure _6 13 generate _16 corre...,ESTIMATING FORCES ON COMPLEX SURFACES
1,Provided is a reflective type display device w...,2009-06-26,13003643,utility,"[Konica Minolta Holdings, Inc.]",[],1.- 5. (canceled)\n\n6. A display device compr...,"{'cpc_classifications': None, 'ipc_classificat...",US,[G06F],...,"[G06F 3/038, G06F 3/041]",2009-06-26,NaN,NaN,2011-05-12,US20110109582,[],"[, characteristic, 13, _16, second_updating_se...",characteristic 13 _16 second_updating_section...,DISPLAY DEVICE
2,A system and method for in-situ introduction o...,2011-01-14,13007335,utility,[SEAGATE TECHNOLOGY LLC],[],1- 21. (canceled)\n\n22. A system comprising: ...,"{'cpc_classifications': None, 'ipc_classificat...",US,[C23C],...,[C23C 14/34],2011-01-14,NaN,NaN,2012-07-19,US20120181165,[],"[, transported, supply, 43, 29, _44, _26, corr...",transported supply 43 29 _44 _26 correspondin...,IN-SITU GAS INJECTION FOR LINEAR TARGETS
3,“METHOD FOR BANK EQUIPMENT REINFORCEMENT AND F...,2011-01-20,13010246,utility,"[TAVARES DE PINHO, Nelson]",[],1. THE “METHOD FOR BANK EQUIPMENT REINFORCEMEN...,"{'cpc_classifications': None, 'ipc_classificat...",US,[B23P],...,[B23P 17/00],2011-01-20,NaN,NaN,2012-07-26,US20120186086,[],"[parts, , formed, chemical_protective_layer_de...",parts formed chemical_protective_layer_define...,METHOD FOR BANK EQUIPMENT REINFORCEMENT AND FI...
4,An information-processing apparatus comprises:...,2011-01-24,13012229,utility,"[NTT DOCOMO, INC.]",[],1. An information-processing apparatus compris...,"{'cpc_classifications': None, 'ipc_classificat...",US,"[H04L, G06F]",...,"[G06F 9/46, H04L 29/06]",2011-01-24,NaN,NaN,2011-07-28,US20110185396,[],"[, priority, low, information-processing_appar...",priority low information-processing_apparatus...,"INFORMATION-PROCESSING APPARATUS, INFORMATION-..."

In [47]:
len(df1)

2842

In [48]:
df1 =  df1.drop_duplicates('application_number', keep = 'first')
len(df1)

2842

In [49]:
df2 = pd.read_csv("office_actions.csv")
df2.head()

C:\Users\prans\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (1,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,app_id,ifw_number,document_cd,mail_dt,art_unit,uspc_class,uspc_subclass,header_missing,fp_missing,rejection_fp_mismatch,...,rejection_103,rejection_112,rejection_dp,objection,allowed_claims,cite102_gt1,cite103_gt3,cite103_eq1,cite103_max,signature_type
0,14150981,100867762,CTFR,2015-10-15,2632,375,219000,0,0,0,...,1,0,0,0,0,0,0,1,2,1
1,14198961,100867788,CTFR,2015-10-15,2699,345,173000,0,0,0,...,1,0,0,0,0,0,0,0,2,1
2,13796589,100867794,CTNF,2015-10-15,3776,606,159000,0,0,0,...,1,0,0,0,0,0,0,0,3,3
3,14673475,100867844,CTNF,2015-10-15,2627,345,175000,0,0,0,...,1,1,1,0,0,0,1,0,4,1
4,14669113,100867850,CTNF,2015-10-15,2666,382,118000,0,0,0,...,0,1,1,0,0,0,0,0,0,1

In [50]:
df2 = df2.drop_duplicates('app_id', keep = 'first')
len(df2)

2188039

In [51]:
df2 = df2.loc[:,['app_id', 'rejection_102', 'rejection_103']]
df2.head()

     app_id  rejection_102  rejection_103
0  14150981              0              1
1  14198961              1              1
2  13796589              0              1
3  14673475              1              1
4  14669113              0              0

In [52]:
df3 = pd.merge(df1, df2, how = 'left', left_on = 'application_number', right_on= 'app_id')
df3.head()
#, validate = 'one_to_one'

,abstract_full,application_date,application_number,application_type,assignees,citations,claims_full,classifications,country,ipc_classes,...,provisional_number,publication_date,publication_number,related_document_numbers,tags,tags_text,title,app_id,rejection_102,rejection_103
0,Techniques for constructing an enhanced model ...,2010-04-28,13002249,utility,[EMPIRE TECHNOLOGY DEVELOPMENT LLC],[],1. A method for constructing a model of a surf...,"{'cpc_classifications': None, 'ipc_classificat...",US,[G06F],...,NaN,2012-11-29,US20120303332,[],"[, determining_pressure, _6, 13, generate, _16...",determining_pressure _6 13 generate _16 corre...,ESTIMATING FORCES ON COMPLEX SURFACES,13002249,0,1
1,Provided is a reflective type display device w...,2009-06-26,13003643,utility,"[Konica Minolta Holdings, Inc.]",[],1.- 5. (canceled)\n\n6. A display device compr...,"{'cpc_classifications': None, 'ipc_classificat...",US,[G06F],...,NaN,2011-05-12,US20110109582,[],"[, characteristic, 13, _16, second_updating_se...",characteristic 13 _16 second_updating_section...,DISPLAY DEVICE,13003643,0,1
2,A system and method for in-situ introduction o...,2011-01-14,13007335,utility,[SEAGATE TECHNOLOGY LLC],[],1- 21. (canceled)\n\n22. A system comprising: ...,"{'cpc_classifications': None, 'ipc_classificat...",US,[C23C],...,NaN,2012-07-19,US20120181165,[],"[, transported, supply, 43, 29, _44, _26, corr...",transported supply 43 29 _44 _26 correspondin...,IN-SITU GAS INJECTION FOR LINEAR TARGETS,13007335,0,1
3,“METHOD FOR BANK EQUIPMENT REINFORCEMENT AND F...,2011-01-20,13010246,utility,"[TAVARES DE PINHO, Nelson]",[],1. THE “METHOD FOR BANK EQUIPMENT REINFORCEMEN...,"{'cpc_classifications': None, 'ipc_classificat...",US,[B23P],...,NaN,2012-07-26,US20120186086,[],"[parts, , formed, chemical_protective_layer_de...",parts formed chemical_protective_layer_define...,METHOD FOR BANK EQUIPMENT REINFORCEMENT AND FI...,13010246,0,1
4,An information-processing apparatus comprises:...,2011-01-24,13012229,utility,"[NTT DOCOMO, INC.]",[],1. An information-processing apparatus compris...,"{'cpc_classifications': None, 'ipc_classificat...",US,"[H04L, G06F]",...,NaN,2011-07-28,US20110185396,[],"[, priority, low, information-processing_appar...",priority low information-processing_apparatus...,"INFORMATION-PROCESSING APPARATUS, INFORMATION-...",13012229,0,1

In [53]:
len(df3)

2842

In [54]:
df3.rejection_103.value_counts()

1    2326
0     516
Name: rejection_103, dtype: int64